owner: source-dream
repo: upptime

sites:
    - name: ymbhp-api
      # slug: ymbhp-api
      url: https://api.sourcedream.cn
    - name: ymbhp-web
      # slug: ymbhp-web
      url: https://www.ymbhp.com
    - name: webhook
      # slug: push
      url: $WEBHOOK_URL
    - name: Broken test
      # slug: broken-test
      url: https://thissitedoesnotexist.koj.co

status-website:
    # cname:
    baseUrl: /upptime
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: 源梦站点监控
    # introTitle: ""
    # introMessage: ""
    navbar:
        - title: Status
          href: /

i18n:
    footer: "This page is created by [sourcedream](blog.sourcedream.cn), powered by [upptime](https://upptime.js.org)"
