owner: source-dream
repo: upptime

sites:
    - name: 源梦百货铺接口
      slug: ymbhp-api
      url: https://api.sourcedream.cn
    - name: 源梦百货铺
      slug: ymbhp
      url: https://www.ymbhp.com
    - name: 无效测试
      slug: broken-test
      url: https://thissitedoesnotexist.koj.co

status-website:
    # cname:
    baseUrl: /upptime
    logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
    name: 源梦站点监控
    # introTitle: ""
    # introMessage: ""
    navbar:
        - title: Status
          href: /

i18n:
    footer: "This page is created by [sourcedream](blog.sourcedream.cn), powered by [upptime](https://upptime.js.org)"
